plugins:
  radon: 
    enabled: true
    config: 
      python_version: 2
      threshold: "B"
  pep8:
    enabled: true

version: "2"         # required to adjust maintainability checks
checks:
  similar-code:
    config:
      threshold: "B"
